export const transactionHistory = [
  {
    id: 1,
    title: 'TakeN\'Eat',
    type: 'Debit',
    status: 'Success',
    date: '2024-02-22T05:03:22.005Z',
    value: 26.5,
    currency: 'DOLLAR',
    channel: 'Online',
    category: 'Food and Drink',
  },
  {
    id: 2,
    title: 'Cash withdrawal',
    type: 'Debit',
    status: 'Success',
    date: '2023-03-25T07:58:22.005Z',
    value: 250,
    currency: 'DOLLAR',
    channel: 'ATM',
    category: 'Withdrawal',
  },
  {
    id: 3,
    title: 'Traveling to Ondo',
    type: 'Debit',
    status: 'Success',
    date: '2024-09-18T05:03:22.005Z',
    value: 10,
    currency: 'DOLLAR',
    channel: 'Transfer',
    category: 'Travels',
  },
  {
    id: 4,
    title: 'Chicken Lovers',
    type: 'Debit',
    status: 'Failed',
    date: '2024-04-20T02:11:55.005Z',
    value: 6.5,
    currency: 'DOLLAR',
    channel: 'Online',
    category: 'Food and Drink',
  },
  {
    id: 5,
    title: 'Dominos',
    type: 'Debit',
    status: 'Success',
    date: '2022-04-09T05:03:22.005Z',
    value: 26.5,
    currency: 'DOLLAR',
    channel: 'In Store',
    category: 'Food and Drink',
  },
  {
    id: 6,
    title: 'Freelance',
    type: 'Credit',
    status: 'Success',
    date: '2022-08-23T05:03:22.005Z',
    value: 3000,
    currency: 'DOLLAR',
    channel: 'Online',
    category: 'Salary',
  },
  {
    id: 7,
    title: 'AT&T',
    type: 'Credit',
    status: 'Success',
    date: '2023-04-22T05:03:22.005Z',
    value: 2000,
    currency: 'DOLLAR',
    channel: 'Online',
    category: 'Salary',
  },
  {
    id: 8,
    title: 'Cash withdrawal',
    type: 'Debit',
    status: 'Success',
    date: '2024-10-12T01:08:22.005Z',
    value: 1000,
    currency: 'DOLLAR',
    channel: 'ATM',
    category: 'Withdrawal',
  },
  {
    id: 9,
    title: 'Dominos',
    type: 'Debit',
    status: 'Success',
    date: '2023-05-20T15:03:22.005Z',
    value: 5,
    currency: 'DOLLAR',
    channel: 'Online',
    category: 'Food Stuff',
  },
  {
    id: 10,
    title: 'Cash withdrawal',
    type: 'Debit',
    status: 'Success',
    date: '2024-10-02T18:25:22.005Z',
    value: 200,
    currency: 'DOLLAR',
    channel: 'ATM',
    category: 'Withdrawal',
  },
  {
    id: 11,
    title: 'Freelance',
    type: 'Credit',
    status: 'Success',
    date: '2024-06-28T21:13:22.005Z',
    value: 100,
    currency: 'DOLLAR',
    channel: 'Online',
    category: 'Salary',
  },
  {
    id: 12,
    title: 'Burger King',
    type: 'Debit',
    status: 'Success',
    date: '2024-07-02T22:03:22.455Z',
    value: 15,
    currency: 'DOLLAR',
    channel: 'Transfer',
    category: 'Food Stuff',
  },
]